// <auto-generated />
using GuitarShop.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GuitarShop.Migrations
{
    [DbContext(typeof(ShopContext))]
    [Migration("20231119213022_Genre")]
    partial class Genre
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GuitarShop.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            Name = "Guitars"
                        },
                        new
                        {
                            CategoryID = 2,
                            Name = "Basses"
                        },
                        new
                        {
                            CategoryID = 3,
                            Name = "Drums"
                        });
                });

            modelBuilder.Entity("GuitarShop.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            CategoryID = 1,
                            Code = "strat",
                            Name = "Fender Stratocaster",
                            Price = 699m
                        },
                        new
                        {
                            ProductID = 2,
                            CategoryID = 1,
                            Code = "les_paul",
                            Name = "Gibson Les Paul",
                            Price = 1199m
                        },
                        new
                        {
                            ProductID = 3,
                            CategoryID = 1,
                            Code = "sg",
                            Name = "Gibson SG",
                            Price = 2517m
                        },
                        new
                        {
                            ProductID = 4,
                            CategoryID = 1,
                            Code = "fg700s",
                            Name = "Yamaha FG700S",
                            Price = 489.99m
                        },
                        new
                        {
                            ProductID = 5,
                            CategoryID = 1,
                            Code = "washburn",
                            Name = "Washburn D10S",
                            Price = 299m
                        },
                        new
                        {
                            ProductID = 6,
                            CategoryID = 1,
                            Code = "rodriguez",
                            Name = "Rodriguez Caballero 11",
                            Price = 415m
                        },
                        new
                        {
                            ProductID = 7,
                            CategoryID = 2,
                            Code = "precision",
                            Name = "Fender Precision",
                            Price = 799.99m
                        },
                        new
                        {
                            ProductID = 8,
                            CategoryID = 2,
                            Code = "hofner",
                            Name = "Hofner Icon",
                            Price = 499.99m
                        },
                        new
                        {
                            ProductID = 9,
                            CategoryID = 3,
                            Code = "ludwig",
                            Name = "Ludwig 5-piece Drum Set with Cymbals",
                            Price = 699.99m
                        },
                        new
                        {
                            ProductID = 10,
                            CategoryID = 3,
                            Code = "tama",
                            Name = "Tama 5-Piece Drum Set with Cymbals",
                            Price = 799.99m
                        });
                });

            modelBuilder.Entity("GuitarShop.Models.Product", b =>
                {
                    b.HasOne("GuitarShop.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
